### ISSUE TITLE
Setup initial project environment

### ISSUE THREAD

**Issue by morkeltry** [astroash/policy-picker#2]
Setup a boilerplate environment ready to customise.
Acceptance Criteria:

- [x]  createreactapp
- [x]  tachyons
- [x]  travis
- [x]  eslint
- [x]  coverage (built-in to React Jest)

**Comment by maxgerber** [comment]
We added a line to our package.json test script which bypassed the weird warning we were getting about the Request Animation Frame polyfill. We removed nyc/codecov because coverage is inbuilt to React-Jest via the command ``` npm run test -- --coverage ```.

Travis is passing.

Setup and development environment working.
