### ISSUE TITLE
Technical Spike - storing data

### ISSUE THREAD

**Issue by astroash** [astroash/policy-picker#5]
Generic components will be created to display the copy. Research needed to decide the best place to store this. Current ideas are:
* in parent state (as objects/arrays)
* in a json file
* as arrays in separate js file

**Comment by maxgerber** [comment]
_Talk with Elias_:
+ As all the data is static, it doesn't enormously matter whether or not you keep the data in a JSON file or by using Redux.
+ Q: Will the imported JSON file be taken into the webpack bundle?
A: Yes

**It seems that for this static data the easiest route would be to store it in a JSON file and import it in where necessary**

**Comment by maxgerber** [comment]
This is a draft of how our JSON data structure might look:
```
{
EC: {
    1: {
      title: 'blah',
      description: 'blahblah',
      imgsrc: '/assets/img.svg',
      snippets: {
        1: {
           title: 'blah',
           desc: 'blah',
           infograph: [
             { imgsrc: 'blah', desc: 'blahblah' }, { imgsrc: 'blah', desc: 'blahblah' },
             { imgsrc: 'blah', desc: 'blahblah' }, { imgsrc: 'blah', desc: 'blahblah' }
           ],
           links: ['link', 'link', 'link']
        }     
      }
    }
  }
}
```
