### ISSUE TITLE
Technical spike - testing React using Jest

### ISSUE THREAD

**Issue by ameliejyc** [astroash/policy-picker#9]
We need to research how to test our React project using Jest.

https://facebook.github.io/jest/docs/en/tutorial-react.html

**Comment by maxgerber** [comment]
_Talk with Elias_:
+ Q: What does testing with React look like?
A: If we get Redux set up, the easiest thing to test would be **Action Creators and Reducers** as they are pure.
+ If we get to the stage where we want to test our components, we can use **Jest's Mock Shallow Renderer/Mock DOM**, which will allow us to render the component to a fake DOM. We can then with a lot of the **Statleless Functional Components by passing them different props and seeing if they react the way that we'd want to.** We can thereby check that certain elements are rendering correctly, e.g. that said component is red on being given certain props. This is like Unit Testing.
If we have a component containing other components, it would be more like Integration Testing.
BTW, Jest documentation is pretty good.
